name: 'google_ads_source_integration_tests'
version: '0.8.0'
profile: 'integration_tests'
config-version: 2

vars:
  ad_stats: "{{ ref('google_ads_ad_stats_data') }}"
  ad_history: "{{ ref('google_ads_ad_history_data') }}"
  ad_group_history: "{{ ref('google_ads_ad_group_history_data') }}"
  campaign_history: "{{ ref('google_ads_campaign_history_data') }}"
  account_history: "{{ ref('google_ads_account_history_data') }}"

seeds:
  google_ads_source_integration_tests:
    google_ads_ad_stats_data:
      +column_types:
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_campaign_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_group_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
